---
- hosts: dev
  become: yes
  remote_user: ec2-user
  tasks:
    - name: Install Apache.
      yum: name={{ item }} state=present
      with_items: 
      - httpd
      - php
      - php-mysql
    - name: Download Wordpress
      get_url: url=https://wordpress.org/latest.tar.gz dest=/var/www/html/wordpress.tar.gz force=yes
    - name: Extract Wordpress
      command: "tar -zxf /var/www/html/wordpress.tar.gz -C /var/www/html --strip-components 1"
    - name: make my directory readable
      file:
         path: /var/www/html
         mode: u=rwX,g=rX,o=rX
         recurse: yes
         owner: apache
         group: apache
    - name: Make sure apache is started now and at boot.
      service: name=httpd state=started enabled=yes